# Generated by Django 6.0.4 on 2026-04-08 13:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(default='case_study', max_length=100)),
                ('category', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('supply_chain', 'Supply Chain'), ('digital_twin', 'Digital Twin'), ('ia_ml', 'IA / ML'), ('healthcare', 'Healthcare')], max_length=100)),
                ('content', models.TextField(blank=True)),
                ('summary', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('document_link', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'knowledge_base',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(blank=True, choices=[('conference', 'Conference'), ('webinar', 'Webinar'), ('workshop', 'Workshop')], max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_virtual', models.BooleanField(default=False)),
                ('event_link', models.URLField(blank=True)),
                ('participants', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='upcoming', max_length=50)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.CharField(max_length=255, unique=True)),
                ('definition', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('technical', 'Technical'), ('business', 'Business'), ('acronym', 'Acronym')], max_length=100)),
                ('related_terms', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'glossary',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='SeniorAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('expertise', models.TextField(blank=True)),
                ('topics', models.TextField(blank=True)),
                ('events_participated', models.TextField(blank=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('contact_info', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
            options={
                'db_table': 'senior_advisors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('potential_value', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='prospect', max_length=50)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('next_action', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'target_companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('challenge', 'Challenge'), ('next_step', 'Next Step'), ('tool', 'Tool'), ('whitepaper', 'Whitepaper'), ('initiative', 'Initiative')], default='initiative', max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='To Do', max_length=50)),
                ('priority', models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], default='Média', max_length=50)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('actual_hours', models.FloatField(blank=True, null=True)),
                ('related_initiative', models.CharField(blank=True, max_length=255)),
                ('document_link', models.URLField(blank=True)),
                ('notion_link', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('target_companies', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Whitepaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published')], default='draft', max_length=50)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('document_link', models.URLField(blank=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('target_audience', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'whitepapers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(default='Usuário', max_length=255)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operations.task')),
            ],
            options={
                'db_table': 'task_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhitepaperComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(default='Usuário', max_length=255)),
                ('text', models.TextField()),
                ('whitepaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operations.whitepaper')),
            ],
            options={
                'db_table': 'whitepaper_comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
